# Generated by Django 4.2.11 on 2024-09-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
