# Generated by Django 4.2.11 on 2024-09-26 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_alter_report_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
