# Generated by Django 4.2.11 on 2024-09-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_report_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='star',
            field=models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], default=3),
        ),
    ]
